name: Geranium

on:
  push:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Geranium
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Theos
        uses: Randomblock1/theos-action@v1.4
      - name: build
        run:  bash ipabuild.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Geranium - extract
          path: |
            /Users/runner/work/${{github.event.repository.name}}/${{github.event.repository.name}}/build/Geranium.tipa
